[providers]
node = '20'

[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs_20', 'npm']
onlyIncludeFiles = [
  'web-app/**',
  'Procfile',
  'railway.toml',
  'railway.json'
]

[phases.install]
cmd = 'cd web-app && npm ci --only=production'

[phases.build]
cmd = 'cd web-app && npm run build'

[start]
cmd = 'cd web-app && npm start'